apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: ${DB_PORT}
      targetPort: ${DOCKER_INTERNAL_PORT}
  type: ClusterIP
